function opt = function_contrast_one_tail(opt)

size_figure = [350,200];
S.fh = figure('units','pixels','position',[300 200 size_figure(1) size_figure(2)],...
    'menubar','none','name','Predictors','numbertitle','off','resize','off');
set(gcf,'color','w'); % white background

% Determine the Subject the Trials X Y and the duration
r = strcat('We will perform a one tail t-test of predictor ',{' '},opt.name{1},' against the baseline activation');
S.text_general = uicontrol('style','text','string',r,'position',[15 160  300 30],...
    'HorizontalAlignment','center','FontWeight','Bold','Backgroundcolor','white');

S.text_alfa = uicontrol('style','text',...
    'units','pix',...
    'position',[15 80 80 20],...
    'string','alpha',...
    'HorizontalAlignment','center','Fontweight','Bold','Background','White');

S.text_alfa_value = uicontrol('style','edit',...
    'units','pix',...
    'position',[130 80 80 20],...
    'string','0.05',...
    'HorizontalAlignment','center','Fontweight','Bold','Background','White');

S.text_name = uicontrol('style','text',...
    'units','pix',...
    'position',[15 40 120 20],...
    'string','Name of Contrast',...
    'HorizontalAlignment','center','Fontweight','Bold','Background','White');


S.text_name_value = uicontrol('style','edit',...
    'units','pix',...
    'position',[130 40 80 20],...
    'string',opt.name,...
    'HorizontalAlignment','center','Fontweight','Bold','Background','White');

% create push button to validate values
uicontrol('parent',S.fh,'Style','pushbutton','Units','pixel',...
    'String','Validate','position',[250 80 65 20],...
    'Callback',{@validate,S});

uiwait(gcf)

    function validate(~,~,S)
        
        %option of imapLMMcontrast
        uiresume(gcf)
        opt.type     = 'predictor beta';
        opt.alpha    = str2double(get(S.text_alfa_value,'String'));
        opt.name     = get(S.text_name_value,'String');
        
        if ishandle(S.fh)
            delete (S.fh)
        end
        
    end

end